export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const CONNECTION_START = 'CONN_START';
export const CONNECTION_SUCCESS = 'CONN_SUCCESS';
export const CONNECTION_FAIL = 'CONN_FAIL';
export const CONNECTION_LIST_START = 'CONN_LIST_START';
export const CONNECTION_LIST_SUCCESS = 'CONN_LIST_SUCCESS';
export const CONNECTION_LIST_FAIL = 'CONN_LIST_FAIL';
export const CONNECTION_TOGGLE_EDIT = 'CONN_TOGGLE_EDIT';
